- hosts: all
  become: yes
  become_user: root
  tasks:
#    - name: Wait for hosts to come up
#      wait_for:
#        timeout: 10
#    - name: Temporarily disable OTC debmirror # Use it when OTC debmirror is down
#      shell: sudo sed -i 's/^deb http:\/\/debmirror/\#deb http:\/\/debmirror/' /etc/apt/sources.list   
    - name: Copy sources.list
      copy:
        src: /etc/apt/sources.list
        dest: /etc/apt/sources.list
    - name: Install fio, iotop
      apt: name={{item}} state=installed 
      with_items:
        - fio
        - iotop
        - python-apt
    - name: Add apt key for Ceph
      apt_key:
        url: https://download.ceph.com/keys/release.asc
        state: present
    - name: Add Ceph repo
      apt_repository:
        repo: deb https://download.ceph.com/debian-luminous/ {{ansible_distribution_release}} main
        state: present
    - name: Update apt
      apt:
        update_cache: yes
    # - name: Install ceph-deploy
    #   apt: 
    #     name: ceph-deploy
    #     state: installed 
    - name: Install ceph packages
      apt: name={{item}} state=installed 
      with_items:
        - ceph-deploy
        - ceph
        - ceph-mds
        - ceph-mgr
        - ceph-mon
        - ceph-osd

- hosts: mgt
  tasks:
#    - name: Print groups
#      debug: 
#        var: groups
#    - name: Print vars
#      debug: 
#        var: vars
#    - name: Print hostvars
#      debug: 
#        var: hostvars
    - name: New Ceph 
      shell: ceph-deploy new {{ groups['mons']|join( " " ) }}
#      with_inventory_hostnames:
#        - mons[1]
#     - name: Install Ceph
# #      shell: ceph-deploy install --release=luminous {{groups["osds"]}}
#       shell: ceph-deploy install --release=luminous {{item}}
#       with_inventory_hostnames:
#         - osds
#         - mons
#         - mgt
    - name: Mon create initial Ceph
      shell: ceph-deploy mon create-initial 
    - name: Admin Ceph
      shell: ceph-deploy admin {{item}}
      with_inventory_hostnames:
        - osds
        - mons
        - mgt
        - clients
    - name: Mgr create Ceph
      shell: ceph-deploy mgr create {{item}}
      with_inventory_hostnames:
        - mons
    # - name: OSD create Ceph
    #   shell: ceph-deploy osd create {{item}}:xvdb
    #   with_inventory_hostnames:
    #     - osds

        # TODO
- hosts: osds
  tasks:
  - name: Copy this-prepare-osds.sh
    copy:
      src: this-prepare-osds.sh
      dest: ~/this-prepare-osds.sh
      mode: 0500
  - name: Prepare OSDs
    shell: ~/this-prepare-osds.sh {{ osd_disks }} {{ vol_prefix }}   # Prepare osd_disks OSDs on the current
                                                                     # host. Assume first disk is
                                                                     # {{ vol_prefix }}b, second
                                                                     # {{ vol_prefix }}c and so on
- hosts: mgt
  tasks:
  - name: Create pool onedata
    shell: sudo ceph osd pool create onedata 128
  - name: Deploy MDS
    shell: ceph-deploy mds create {{ groups['mons'][0] }}
  - name: Create pool cephfs_data
    shell: sudo ceph osd pool create cephfs_data 128
  - name: Create pool cephfs_metadata
    shell: sudo ceph osd pool create cephfs_metadata 128
  - name: Create cephfs
    shell: sudo ceph fs new cephfs cephfs_metadata cephfs_data
  - name: Crush tunables hammer
    shell: sudo ceph osd crush tunables hammer
  - name: Enable dashboard
    shell: sudo ceph mgr module enable dashboard

- hosts: ops
  tasks:
  - name: Copy /etc/hosts
    become: yes
    become_user: root
    copy:
      src: /etc/hosts
      dest:  /etc/hosts
      mode: 0644
  - name: Copy keyring
    copy:
      src: ~/ceph.client.admin.keyring
      dest:  ~/ceph.client.admin.keyring
      mode: 0600
  - name: Create /mnt/ceph
    become: yes
    become_user: root
    file:
      path: /mnt/ceph
      state: directory
      mode: 0755
  - name: Get client.admin keyring
    shell: tail -1 ~/ceph.client.admin.keyring | awk '{print $3}'
    register: keyring
#  - debug: msg={{keyring}}
  - name: Mount CephFS
    become: yes
    become_user: root
    mount:
      path: /mnt/ceph
      fstype: ceph
      src: "{{ groups['mons'][0] }}:6789:/"
      opts: "name=admin,secret={{keyring.stdout}}"
      state: mounted
