- hosts: clients
  tasks:
    - name: Copy /etc/hosts
      become: yes
      become_user: root
      copy:
        src: /etc/hosts
        dest:  /etc/hosts
        mode: 0644
    - name: Copy keyring
      copy:
        src: ~/ceph.client.admin.keyring
        dest:  ~/ceph.client.admin.keyring
        mode: 0600
    - name: Create /mnt/ceph
      become: yes
      become_user: root
      file:
        path: /mnt/ceph
        state: directory
        mode: 0755
    - name: Get client.admin keyring
      shell: tail -1 ~/ceph.client.admin.keyring | awk '{print $3}'
      register: keyring
      #  - debug: msg={{keyring}}
    - name: Mount CephFS
      become: yes
      become_user: root
      mount:
        path: /mnt/ceph
        fstype: ceph
        src: "{{ groups['mons'][0] }}:6789:/"
        opts: "name=admin,secret={{keyring.stdout}}"
        state: mounted
    - name: Install oneclient
      shell: curl -sS  http://get.onedata.org/oneclient.sh | bash
    - name: Create onedata dir
      file:
        state: directory
        path: onedata
    - name: Mount onedata
      shell: oneclient -H "{{groups['ops'][0]}}" -t "{{atoken}}" --force-proxy-io onedata 

